/**
 * Sample DER data for the ASN.1 Explorer.
 * The tiny sample is raw base64 DER; cert samples are real self-signed PEM.
 */

export interface Sample {
  label: string;
  /** Base64-encoded DER bytes, or full PEM text */
  data: string;
}

export const SAMPLES: Sample[] = [
  {
    label: "BasicConstraints (tiny)",
    // SEQUENCE { BOOLEAN TRUE, INTEGER 0 }
    data: "MAYBAf8CAQA=",
  },
  {
    label: "RSA Certificate",
    data: `-----BEGIN CERTIFICATE-----
MIIDiTCCAnGgAwIBAgIUVrZNUbElZPH1/1sd6nc6UmD5YOUwDQYJKoZIhvcNAQEL
BQAwVDELMAkGA1UEBhMCVVMxFTATBgNVBAoMDERpZ2lDZXJ0IEluYzEuMCwGA1UE
AwwlRGlnaUNlcnQgVmVyaWZpZWQgTWFyayBSU0E0MDk2IFNIQTI1NjAeFw0yNjAz
MDgwNzIyMDFaFw0yNzAzMDgwNzIyMDFaMFQxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
DAxEaWdpQ2VydCBJbmMxLjAsBgNVBAMMJURpZ2lDZXJ0IFZlcmlmaWVkIE1hcmsg
UlNBNDA5NiBTSEEyNTYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCz
nUQXw//u1rMM7m/J3nQkgOmT7rNluDgZQwOCiTl185qVGn48zoX6ICo7+Gs6Gal0
CmmdgnmR4pFFHMwiDXuXrHt2ZLK0sNVThqlJG74Jjr8Xmk1HMyjoxEeyu8fyMXM7
coUF2RwL8Dt6+eUuRAv0Q7cKwZTlCX4AUjAXnrJ7TeQ8qm4bJUMxZ8BrOU/dk7ko
kicfxpJmy89sJR8xRQxzrPrntoVm0aiAocACG3zRY2rXgu5Etn0GZLOLh/+BGrAD
ZtLLmkvPshEea4RkFUgRhdYPBcwM7YKOVAaZyPseIgH2wRLYhJUTty2AAyrqrfj8
BqZ+goxW7foXUuHodp99AgMBAAGjUzBRMB0GA1UdDgQWBBSsBBjTo6ou7LBw8308
MqANsGYO3DAfBgNVHSMEGDAWgBSsBBjTo6ou7LBw8308MqANsGYO3DAPBgNVHRMB
Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCs74Eirqna2E+BpJAeX1WV3HRb
Qemh5jlEexZGioRN5c7215r1hn5adFyn3FF8CimDdBbY9pzu2ThUnuv8Tsu+bzEa
4BOeClQRoqajzpp1x5UQ1h1DhBUlxSYXaKEEmi5lowx+CfydUxjBHk9bZh8mdugV
WWfjQpore+l1l3SJcAIzhl76Ve0DrS+CNfPg+DlXVd6AYdkUJcgvGThzXMjSAOod
Y74lO7G8RQTWu0TBGBqyTDWSLdoTUYEjVQb87KBEnictfW6nRMKuHp87/GF9DNV/
5X5sB+sTrpSgBzvF6PVQpjLSeYiU1c6DPN+5YUJcmr24AXZxa3mxGyJvbhv9
-----END CERTIFICATE-----`,
  },
  {
    label: "EC Certificate",
    data: `-----BEGIN CERTIFICATE-----
MIIBgTCCASegAwIBAgIUP5XqoFlLM37MuNpuCdF4EHrmRP4wCgYIKoZIzj0EAwIw
FjEUMBIGA1UEAwwLZXhhbXBsZS5jb20wHhcNMjYwMzA4MDcyMTU5WhcNMjYwNjA2
MDcyMTU5WjAWMRQwEgYDVQQDDAtleGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABOqhFZG4KvYHBcxS1HPMdNWjoFAZkiQ0rU4zVLnbnJuf5u1EgAu3
6/F+IThhJE4wmG9OCBAGQjR+TCCDJQd+ZrKjUzBRMB0GA1UdDgQWBBRxuqeERRH1
wZRgHLxTGGsT4flQwDAfBgNVHSMEGDAWgBRxuqeERRH1wZRgHLxTGGsT4flQwDAP
BgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIQCjdhzvatM2lLACmSOg
s0rutgnBRqPiPi/x8HkghjGMcAIgHCpkG4wvKLuTDpJfG7ECjBB+btDXwTWQFErl
nOeE6ek=
-----END CERTIFICATE-----`,
  },
];
